import type { Metadata } from 'next';
import { Phone, Mail, MessageCircle, MapPin, Clock, Instagram, Linkedin } from 'lucide-react';
import TikTokIcon from '@/components/icons/TikTokIcon';
import SectionHeading from '@/components/ui/SectionHeading';
import RevealOnScroll from '@/components/ui/RevealOnScroll';
import ContactForm from '@/components/forms/ContactForm';
import { getContent } from '@/lib/content-store';
export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'İletişim', description: 'Telefon, e-posta veya iletişim formu üzerinden ulaşın.' };
export default async function ContactPage() { const { site } = await getContent(); const text = site.texts.contactPage; return <div className="pb-24 pt-36 sm:pt-44"><div className="container-site"><SectionHeading eyebrow={text.eyebrow} title={text.title} description={text.description} className="mb-14" /><div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div className="space-y-8">
  <RevealOnScroll><div className="paper-card p-7"><h2 className="font-display text-lg text-ink">{text.infoTitle}</h2><ul className="mt-5 space-y-4 text-sm"><li className="flex items-start gap-3"><Phone className="mt-0.5 h-4 w-4 shrink-0 text-clay" /><a href={`tel:${site.phone}`} className="text-ink-soft hover:text-clay">{site.phoneDisplay}</a></li><li className="flex items-start gap-3"><Mail className="mt-0.5 h-4 w-4 shrink-0 text-clay" /><a href={`mailto:${site.email}`} className="text-ink-soft hover:text-clay">{site.email}</a></li><li className="flex items-start gap-3"><MessageCircle className="mt-0.5 h-4 w-4 shrink-0 text-clay" /><a href={`https://wa.me/${site.whatsapp}`} target="_blank" rel="noopener noreferrer" className="text-ink-soft hover:text-clay">WhatsApp’tan yazın</a></li><li className="flex items-start gap-3"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-clay" /><span className="text-ink-soft">{site.address.street}, {site.address.district}/{site.address.city} {site.address.postalCode}</span></li></ul></div></RevealOnScroll>
  <RevealOnScroll delay={0.1}><div className="paper-card p-7"><h2 className="flex items-center gap-2 font-display text-lg text-ink"><Clock className="h-4 w-4 text-clay" /> {text.hoursTitle}</h2><ul className="mt-5 space-y-2.5 text-sm">{site.workingHours.map((wh) => <li key={wh.day} className="flex items-center justify-between gap-4 text-ink-soft"><span>{wh.day}</span><span className="font-mono text-xs text-ink">{wh.hours}</span></li>)}</ul></div></RevealOnScroll>
  <RevealOnScroll delay={0.2}><div className="paper-card p-7"><h2 className="font-display text-lg text-ink">{text.socialTitle}</h2><div className="mt-4 flex gap-3">{[{ href: site.social.instagram, Icon: Instagram, label: 'Instagram' }, { href: site.social.linkedin, Icon: Linkedin, label: 'LinkedIn' }, { href: site.social.youtube, Icon: TikTokIcon, label: 'TikTok' }].map(({ href, Icon, label }) => <a key={label} href={href} target="_blank" rel="noopener noreferrer" aria-label={label} className="flex h-10 w-10 items-center justify-center rounded-full border border-ink/10 text-ink-soft transition-colors hover:border-clay hover:text-clay"><Icon className="h-4 w-4" /></a>)}</div></div></RevealOnScroll>
  <RevealOnScroll delay={0.3}><div className="aspect-video overflow-hidden rounded-xl2 border border-ink/[0.06] bg-sage-50"><div className="flex h-full items-center justify-center px-6 text-center font-mono text-xs uppercase tracking-wide text-sage-600">{text.mapText}</div></div></RevealOnScroll>
</div><RevealOnScroll delay={0.15}><ContactForm /></RevealOnScroll></div></div></div>; }
